apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tr39q9xvp-go 
  janus-idp.io/tekton: tr39q9xvp-go
  backstage.io/kubernetes-id: tr39q9xvp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tr39q9xvp-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml