apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tr39q9xvp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tr39q9xvp-go 
  name: tr39q9xvp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tr39q9xvp-go 
